### ISSUE TITLE
2016년 05월 11일 개발 예제 추천 

### ISSUE THREAD

**Issue by chohankyun** [chohankyun/klbn_python_study#1]
안녕하세요. 조한균입니다.
오늘 30분정도 간단하게 이론 정리 하고.
뭔가 간단한 프로그램을 1시간 동안 만들어 보면 좋을것 같은데, 
어떤 프로그램을 만들지 추천 받습니다.

**Comment by chohankyun** [comment]
오늘 아무도 글을 안쓰셨네요..ㅋㅋ

**Comment by kolon-pjin** [comment]
수고하셨습니다.

**Comment by yshyun** [comment]
오늘 스터디에서 파이썬 기초 설명해주느라 고생 많으셨습니다~

**Comment by chohankyun** [comment]
박대리가 이슈 클로즈해서 다시 열겠습니다.

**Comment by eversafe** [comment]
AWS S3 를 이용한 팀 웹하드는 어떤가요? 
참고  : https://devcenter.heroku.com/articles/s3-upload-python
너무 AWS 스러워서 좀 그렇긴 하네요. =_=

**Comment by chohankyun** [comment]
dropdox 같은거 만들자는 말인가?

**Comment by eversafe** [comment]
네, 드롭박스같은건데~ 인증부분을 IAM으로 처리하면 좀 빠르게 개발가능할꺼 같아요.
