### ISSUE TITLE
static file 위치는 어디로 잡아야 하나요?

### ISSUE THREAD

**Issue by toriworks** [chohankyun/klbn_python_study#10]
js, css, image 등과 같은 static file의 위치는 어디로 잡아야 하나요?

Q1) settings.py에 보면 STATIC_URL = '/static/' 라고 있는데, settings.py는 전체 app들이 참조하는 파일이라고 생각해 보면 root 디렉토리에 /static/ 으로 만들면 되는지 궁금합니다.

Q2) 1번 질문이 맞다면, app별로는 static 디렉토리를 만들 수 없는지 궁금합니다. 물론 /static/ 안에 폴더를 만들면 되겠지만, 혹시나 app별로 static 디렉토리를 가지는게 가능한지 궁금합니다.

**Comment by chohankyun** [comment]
어제 오셨으면 다 같이 설명하려고 했는데..ㅋㅋㅋ
1)맞습니다 root  에서 static 디렉토리 만들어서 사용하시면 됩니다.
2)app별로 static 디렉토리를 만드는건 해본적이 없어서 정확히 말은 못드리겠습니다. 뭐 여러가지 설정을 하면 가능할것 같은데, 정확히는 모르겠습니다. 
하지만 그건 별로 좋은 방법이 아닌것 같습니다.
이유는 일단 static 파일들은 외부에서 언제든지 접근 가능한 파일들입니다.
그리고 *.py는 사실 외부에서 직접전근하면 안되는 파일이죠. 
하여튼 일반적으로 static 파일을 위치시키는 방법은 두가지가 있습니다.

첫째는, 파일별로 static 폴더를 만들어서 위치시키는 방법 예) css, js, img, html 등 프로그램 규모가 작으면 이렇게 해도 됩니다. 그러나 저는 별로 추천하지는 않습니다.

두번째는, static 폴더 밑에 app별 폴더를 만들어서 위치 시키는 겁니다. 예) login, member, board 등
밑에 css, html, img, js 등을 위치 시킵니다. 물론 공통으로 사용되는 파일은 common 등의 폴더를 만들어서 위치시킵니다.

**Comment by toriworks** [comment]
그러게요. 갔었어야 했는데... 프로젝트 중이라서 눈치가 엄청 보이네요.

추가적인 질문인데, 위의 질문과는 약간 별개의 내용이긴 한데요. Django로 API를 만드시면서, API 보안은 어떻게 하셨는지 궁금합니다.

API에 대한 Authentication이나 Authorization이 중요할 것 같은데요, 실제 Django로 어떻게 API 보안을 하셨는지 궁금합니다.

**Comment by chohankyun** [comment]
API 라고 하면 어떤걸 말하시는건지?
일단 장고는 웹어플리케이션 프레임워크 입니다.
말인즉은, 브라우저로 호출해서 웹페이지를 보여주는거죠.
일단 이게 기본이고, 
흔히들 말하는 RESTFUL API를 만들기 위해서는 
Django REST Framework 를 사용합니다.
물론 django 에서 템플릿 방식을 사용 안하고 요청이 오면 json or xml 로 리턴하게 한다면
REST API를 만들수 있죠,
어쨌건 웹페이지 보안은 저도 CSRF 와 세션으로만 처리 했습니다.
우리가 흔히 말하는 API 보안을 하려면 사실 token 을 사용해서 해야 할겁니다.

**Comment by toriworks** [comment]
네, RESTful API를 말씀 드린거구요. 저희 모바일쪽의 경우는 대부분 모바일 디바이스와의 통신을 RESTful로 구성하거든요. 

말씀대로라면 우선 RESTful API를 만들기 위해서는 Django REST Framework을 사용해야 하는거네요.
token 부분은 OAuth 랄지 그런류로 고려를 해봐야겠네요.

답변 감사드려요^^
