### ISSUE TITLE
python은 WAS가 필요 없나요?

### ISSUE THREAD

**Issue by NeGaMotSalA** [chohankyun/klbn_python_study#12]
java 같은 경우는 webtob 라든가 tomcat 등의 was가 필요한데 python은 어떤가요?

**Comment by chohankyun** [comment]
일단 간단하게 얘기하면 django 는 web server 가 필요합니다.
이제 길게 얘기를 하면, 
일반적으로 우리가 web application 을 만들때는  web server 와 was 를 필요로 합니다.
어떤것은 web server 만 있어도 되고, 어떤것은 was 만 있어도 되고,  또 어떤것은 web server , was 두개가 있어야 하고요.
일단 기본적으로 web server 는 static content(html, css, js, image)를 웹에서 처리 하기 위해서 필요합니다.
was(web application server) 는 dynimic content(jsp) 를 처리하기 위해서 필요합니다.
일반적으로  was  라 하면 대부분은 jsp 를 동작시키기 위한 것이라고 생각해도 됩니다. 
was 에는 jsp, servlet 엔진과 j2ee 에 명시되어 있는 여러가지 기능들을 포함합니다.

그럼  php, python 등은 어떻게 동작 하는가를 알면 어떤것이 필요한지 알수 있습니다.
일단 위에서 말한것 처럼 static content 를 웹에서 동작 시키려면 web server(apache, nginx, webtob, etc) 가 필요합니다. webtob 는 web server 에 속하고, jeus 가 was 에 속합니다.

그리고 php, python 을 동작시키기 위한 엔진이 필요하죠, 그리고 web server 와 php, python 엔진을 
연결해주는 프로그램이 필요합니다. 이게 바로 우리가 알고 있는 cgi, fcgi, wsgi , etc 이 있죠

python 을 예로 들면 브라우저로 요청을 보내면 web server 가 받고 web server 는 데이터 타입이라던지, 설정을 보고 wsgi 를 호출하고 그리고 wsgi 는 python 프로그램을 호출합니다.
