### ISSUE TITLE
컬럼을 하나 추가하려면?

### ISSUE THREAD

**Issue by NeGaMotSalA** [chohankyun/klbn_python_study#3]
테스트로 models.py에 title, content컬럼 추가했었는데
컬럼을 하나 추가하려먼 어떠한 절차로 해야 하나요...?
## 그냥 했더니...

You are trying to add a non-nullable field 'etc' to board without a default; we
can't do that (the database needs something to populate existing rows).
Please select a fix:
 1) Provide a one-off default now (will be set on all existing rows)
 2) Quit, and let me add a default in models.py
Select an option: 1
Please enter the default value now, as valid Python
The datetime and django.utils.timezone modules are available, so you can do e.g.
##  timezone.now()

이런 메세지 나오더라구요.

0001_initial.py 파일 지우고 makemigrations 하니까 다시 만들어지는것 같던데...
python manage.py migrate <--요놈 날려도 db.sqlite3 업데이트 안되는것 같고
쉽지가 않군요.

**Comment by chohankyun** [comment]
1) 선택하고 , default 값으로 '' 넣으면 추가 됩니다.

**Comment by chohankyun** [comment]
만약 0001_initial.py  파일을 지웠다면, django_migrations 테이블에 있는 app 명 row 를 지워야  
migrate 명령어가 적용됩니다.
