### ISSUE TITLE
django project create

### ISSUE THREAD

**Issue by NeGaMotSalA** [chohankyun/klbn_python_study#4]
C:\dev_study\projects>django-admin startproject study
'django-admin'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그
배치 파일이 아닙니다.

C:\dev_study\projects>ython django-admin startproject study
'ython'은(는) 내부 또는 외부 명령, 실행할 수 있는 프로그램, 또는
배치 파일이 아닙니다.

C:\dev_study\projects>python django-admin startproject study
python: can't open file 'django-admin': [Errno 2] No such file

C:\dev_study\projects>python -m django startproject study

C:\dev_study\projects>dir
 C 드라이브의 볼륨에는 이름이 없습니다.

**Comment by chohankyun** [comment]
이건 잘 모르겠는데요?  지금도 안생겼어요?
