### ISSUE TITLE
urls.py와 templates에 있는 html이 어떠한 원리로 연결되는 건가요?

### ISSUE THREAD

**Issue by NeGaMotSalA** [chohankyun/klbn_python_study#6]
urls.py에는 

urlpatterns = patterns('',
  url(r'^$', views.ServerList.as_view(), name='server_list'),
  url(r'^new$', views.ServerCreate.as_view(), name='server_new'),
  url(r'^edit/(?P<pk>\d+)$', views.ServerUpdate.as_view(), name='server_edit'),
  url(r'^delete/(?P<pk>\d+)$', views.ServerDelete.as_view(), name='server_delete'),
)

이런식으로 작성하는데...

실제 templates의 html 파일명은 

server_form.html
server_confirm_delete.html
server_list.html

이런식으로 되어있쟎아요. 
패던과 파일명의 연결고리가 없는것 같은데, 신기하네요.

**Comment by chohankyun** [comment]
ServerList(ListView) 이런식으로 되어 있을텐데.
ListView 를 상속 받는다는 의미고 이 ListView 를 타고 들어가면 또 여러개의 클래스를 상속받는데
그중에 하나에 어떤 html 리턴하라는 것이 선언되어 있어요, 물론 이부분은 수정해서 자기기 원하는 
html 로 리턴하게 할수도 있습니다.
class based view 를 이해 하면 알 수 있습니다.
