### ISSUE TITLE
이번주 모임은 오늘?

### ISSUE THREAD

**Issue by NeGaMotSalA** [chohankyun/klbn_python_study#7]
저번주에 별다른 공지가 없었기 때문에 월요일(오늘)에 모임을 하는거겠죠?

오늘은 진행하고 있는 프로젝트 회식일이라 아쉽게도 참석 못할것 같습니다.

나머지 분들은 다 참석 가능하신가요....?

**Comment by RyuTaeYeon** [comment]
저도 개인사정이 생겨 금일 교육에 참석이 어려울 듯 합니다.

게다가 공교롭게도 여의도에서 신청한 3분(김보영, 김미선, 류태연)

모두 참석이 불가능하다고 하셔서

혹시 이번 주 모임을 다른 날로 바꿔서 진행할 순 없을지 의견을 여쭙고자 합니다.

**Comment by chohankyun** [comment]
저는 오늘 안해도 상관없을것 같습니다.
그런데 이건은 이슈 발행 하는것 보다 메일로 보내서 의견 수렴하는게 좋을것 같습니다.
