### ISSUE TITLE
현재 예제에서 delete가 잘 되는 걸까요?

### ISSUE THREAD

**Issue by phpdoumi** [chohankyun/klbn_python_study#9]
다른 건 다 되는데, delete에서 confirm을 눌러도 변화가 없습니다.
지금 소스 이상 없는지 확인만 부탁합니다..
이상 없으면 다시 찾아 볼께요..^^

**Comment by chohankyun** [comment]
만약 에러가 나지 않는다면, 데이타 베이스에서 직접확인해 보세요.
화면상으로는 알아보고 힘들수도 있습니다.

**Comment by phpdoumi** [comment]
아뇨...이거 만들어서 해 봤는데 삭제만 안되서 잘되는건데 내가 옮기기를 잘못 옮긴건지 싶어서..확인차 드린 내용입니다.
이걸로 실행해 보니 되드라....정보만 주시면...^___^

**Comment by chohankyun** [comment]
아하.ㅋㅋㅋ

**Comment by phpdoumi** [comment]
되는건가요? 답은 안 주시고. ㅠㅠ

**Comment by chohankyun** [comment]
제가 지금 피스를 포멧중이라.ㅋㅋ
원래는 잘되는겁니다..

**Comment by phpdoumi** [comment]
그럼 다시 체크해 보겠습니다...근데 다 되는데 왜 그것만 안될까? ^^

**Comment by chohankyun** [comment]
콜솔창에 나오는 메시지랑 화면에 나오는 메시지를 알려주세요.

**Comment by phpdoumi** [comment]
하하하 이런....
user_confirm_delete.html 파일에서 html lang="ko"를 html lang='ko" 이렇게 했다고 안되네...ㅠ.ㅠ
잘되는 거 확인 했습니다...수고하세요...

**Comment by chohankyun** [comment]
하하하..정말 어려운걸 찾으셨네요..
이건 왠만해서는 못차는 오류인데..

**Comment by NeGaMotSalA** [comment]
5분 넘게 보고서야 뭐가 잘못됐는지 알았네요. ㅋㅋㅋ
커맨트는 메일 안오게 할 순 없나요..?? T,.Ta

**Comment by chohankyun** [comment]
커맨트 메일 안오게 할려면 옆에 unsubscrbe 클릭하면 되요.ㅋㅋㅋ
